### PR TITLE
Fix for unexpected Shift+Enter behavior

### LINKED ISSUE #5: Unexpected Shift+Enter Behavior
Shift+Enter will only send the command to the printer if the cursor is at the end of the line, if the cursor is in the middle of a line it will split that line then send the command to the printer. This makes editing lines of code more complicated than the process should be as one has to pay careful attention to the cursor location when hitting enter.

### PR DESCRIPTION
**Pull request by dchauran**
Fixes #5

### CODE REVIEW

**Comment by jneilliii** [comment]
Thanks for the contribution @dchauran

**Comment by jneilliii** [comment]
Shouldn't the handleKeyUpMultiline also be removed from the knockout data binding though?

**Comment by jneilliii** [comment]
I removed the keyup event hook binding altogether since it was no longer needed.

**Comment by dchauran** [comment]
> Shouldn't the handleKeyUpMultiline also be removed from the knockout data binding though?

Thanks, good catch and tanks for taking care of it. I quickly skimmed the file and missed that.

**Pull request merged**
